name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
      # to be used by fork patch-releases ^^
      - 'v*.*.*-*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.18.x

      - name: Prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF#refs/tags/}
            echo ::set-output name=tag_name::${TAG}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Run GoReleaser
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_KEY }}

       - name: install fpm
          run: |
            sudo gem i fpm -f && fpm --version

       - name: fpm build rpm
         run: fpm -s dir -t rpm -n heimdall -v $(TAG)


       - name: fpm build deb
         run: fpm -s dir -t deb -n heimdall -v $(TAG)

       - name: checksum build
         run: md5sum heimdall.rpm.$(TAG)

       - name: checksum deb
         run: md5sum heimdall.deb.$(TAG)
